### ISSUE TITLE
Hardware required: what is disk size?

### ISSUE THREAD

**Issue by PSLLSP** [monero-ecosystem/PiNode-XMR#106]
I read Hardware requirements for SBC and I cannot find any note about disk size. I assume that a lot of disk space will be required to store local copy of blockchain but I cannot find any note about that in "Hardware requirement". What disk to order, what is minimum/recommended size, like 128GB or 512GB. And I cannot find any note about size of microSDHC for SBC builds, like RPI or Odroid; is 8GB microSDHC card good enough? In the case that external disk is required, it will be the nice to use "small" microSDHC card only to run bootloader and the rest of system and data should be stored on external disk; external SSD disks are more reliable than microSDHC cards...

**Comment by shermand100** [comment]
Hi, I believe the Monero blockchain has grown about 30GB per year consistently for a few years and is a good ball park figure for growth. Add this to what was 170GB when I last checked in July and I'd start with at least 256GB for blockchain storage. May something around the 300GB mark for a bit more future proofing.

It is possible to run a pruned node however and get that value below 60GB I believe.

The microSD can be 16GB and then allows plenty of breathing room for future updates. Depending on the OS 8GB can be too small as the Ubuntu server image comes in at about 7GB as it includes snaps which bloat it a little. Others may be similar depending on developer.

Hope that helps.
A current modest setup is listed here 

https://github.com/monero-ecosystem/PiNode-XMR/wiki/Hardware#example-hardware-build--

**Comment by shermand100** [comment]
https://github.com/monero-ecosystem/PiNode-XMR/wiki/Hardware#storage-requirements

Added storage requirements to the docs with examples.
