### ISSUE TITLE
discrepency between master/p2pool-new-ver.sh (v370) and ubuntuServer-20.04/update-p2pool.sh (v361)

### ISSUE THREAD

**Issue by alicedb2** [monero-ecosystem/PiNode-XMR#107]
`p2pool-new-ver.sh` is set to 370, but `ubuntuServer-20.04/update-p2pool.sh` line 55 still `git checkout tags/3.6.1` instead of `tags/v3.7`. As a result p2pool isn't upgraded to the expected version and you end up with a mismatch between `CURRENT_VERSION_P2POOL=370` stored in `~/current-ver-p2pool.sh` and the actual version of p2pool. 

```
pinodexmr@PiNodeXMR:~$ cat current-ver-p2pool.sh 
#!/bin/bash
CURRENT_VERSION_P2POOL=370

pinodexmr@PiNodeXMR:~$ p2pool/build/p2pool --version
2023-10-14 17:26:17.6400 Log started
P2Pool v3.6.1 (built with GCC/11.4.0 on Oct 14 2023)
2023-10-14 17:26:17.6437 Log stopped
```

Once fixed users will need to manually edit `current-ver-p2pool.sh` back to 361 for the update procedure to work correctly.

**Comment by shermand100** [comment]
Sorry about that, good spot.

Corrected just now at https://github.com/monero-ecosystem/PiNode-XMR/commit/1f9b522daee4256e3ec4f449d60280c5b060b630

**Comment by shermand100** [comment]
P2Pool update to v3.8 added to PiNodeXMR today. All three files updated. Closing this.
