### ISSUE TITLE
Sync Status Showing as Idle(Force Web Server to disallow web caching)

### ISSUE THREAD

**Issue by ChiefGyk** [monero-ecosystem/PiNode-XMR#14]
I am noticing since the latest update sync status is always showing as idle on my Odroid HC2 and also the CPU temperature is not appearing. However iotop is definitely showing quite a bit of disk activity from monero. I'm trying to poke around and see where monero dumps logs or such because it looks like you moved it 

images
https://ibb.co/ChP1Rqp

https://ibb.co/VNYLzDG

**Comment by ChiefGyk** [comment]
Upon further inspection, it looks like my browser was caching things... Interesting. I may look into disable web browser caching at Apache and then eventually Nginx when I get around to working on that.

**Comment by shermand100** [comment]
Hi, this had been a long standing problem in that scripts for the most commonly used statistics are used every minute to update status:
Sync Status,
Tx pool Stats
Connected peer status

Less commonly changed every 4hrs:
Monero version
Disk usage

All these timings are managed by user pinodexmr crontab.
Crontab runs a script for each command (hence it looks busy), and each scipt outputs it's response to the /var/www/html directory for the web-ui to pick up and display.

I have made an attempt at disabling cache, but via instructions to the browser in the header of the html files:

/var/www/html/node_status.html example...

    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
	   <meta http-equiv="Pragma" content="no-cache" />
	   <meta http-equiv="Expires" content="0" />

Which was derived from a google search similar to https://stackoverflow.com/questions/49547/how-do-we-control-web-page-caching-across-all-browsers

In hind sight there are many things wrong with how these stats are produced and managed. Only typing this out do I see how ridiculous it is. I'm sure JSON is the way to go, and requests would be better off batched into a single script for 1minute commands and another script for 4hr command etc.

Thoughts on this or the caching?

**Comment by ChiefGyk** [comment]
There probably are better ways to optimize it but that's not my forte.
However I am noticing the sync seems to be stuck on my Odroid often and am troubleshooting

**Comment by shermand100** [comment]
This I see as the biggest flaw for user experience and will be my next target for improvement.

Plan:

Overhaul the way the stats are generated and move to a JSON calling method. This will also reduce resource load as in some cases one JSON requests covers several current stats commands . (When node is running you can find multiple instances of Monerod listed `htop`, most of these are status calls. It is very inefficient.

These overhauled status calls as JSON text will then be better managed through disabled caching, perhaps at a server level. The current HMTL level prevention of caching hasn't had the effect I expected. And perhaps an auto-refresh of the status page.

linked to https://github.com/monero-ecosystem/PiNode-XMR/issues/7

**Comment by shermand100** [comment]
Disables cache via .htaccess

https://github.com/monero-ecosystem/PiNode-XMR/commit/2a35045bbb71907edf7f9f65190ed74dd004da34
