### ISSUE TITLE
Odroid XU4/HC1/HC2 as Tested Hardware

### ISSUE THREAD

**Issue by ChiefGyk** [monero-ecosystem/PiNode-XMR#17]
We can mark the Odroid XU4/HC1/HC2 platform as tested hardware with the following notes:

XU4 with eMMC module preferred due to performance reasons
HC1/HC2 Require the Serial UART adapter as they have they video output connections. I have been using Gtkterm on /dev/ttyUSB0 @ 115200 bauds 8 bits no parity, no flow control, 1 stopbits. You can use minicom as well but I found that to be a headache

I run an HC2 and recommend at least a 500GB NAS hard drive or 500GB SSD, I am using a 1TB Seagate Iron Wolf on both my production and testing version with 16GB MicroSD cards. I used the official Odroid Wireless N adapter for initial setup using nmcli, and then hard wired it to ethernet to finish it up. There was a significant speed difference between wireless and wired as was expected. 

The HC1 and HC2 have the advantage over the XU4 and Pi's by having a truly native SATA connector for 2.5" drives in the HC1 and 3.5" in the HC2. I recommend the RTS battery backup as it will help preserve the clock in case of reboot but not absolutely necessary if NTP is setup appropriately. 
They will need to make sure the power adapter chosen can appropriately power their individual devices as well. 

I used the Buster Minimal 5.4.y image from here https://www.armbian.com/odroid-hc1/#kernels-archive-all 

The HC1 and HC2 are the Odroid merely with no video output and a native SATA connection and no eMMC capability. That's why the XU4 can also be qualified. I have an actual XU4 in front of me but zero reason to put online as of right now

**Comment by shermand100** [comment]
Hardware Wiki updated. Referenced to here for the notes.

https://github.com/monero-ecosystem/PiNode-XMR/wiki/Hardware/09cda3719553af6816fcf4b3d79d996837b7d469

Thanks for testing

**Comment by shermand100** [comment]
Adding note for future Odroid HC1/2 users: From telegram user mechanic41turk reports Odroid HC1 with HDD took 60 days to sync from block 0 to 2670141.

As always I recommend transferring the blockchain from a PC via FTP/SFTP on these low power devices to avoid this delay, but glad he was able to put old hardware to good use.
