### ISSUE TITLE
Out Peers need to be increased

### ISSUE THREAD

**Issue by ChiefGyk** [monero-ecosystem/PiNode-XMR#21]
We need to have options higher that 16 as a maximum, some guides say 32 may be optimal but I will need to tinker some more. I will do some additional testing in command line but this is yet another to do

**Comment by ChiefGyk** [comment]
Tested and found to work as intended as it's merely numbers changed.

**Comment by shermand100** [comment]
Options for 24 and 32 peers added in above commit. Will commit to armbian branch too
