### ISSUE TITLE
Temperature not displaying in WebUI on Armbian/Odroid

### ISSUE THREAD

**Issue by ChiefGyk** [monero-ecosystem/PiNode-XMR#25]
Temperature doesn't display in WebUI on my HC2 version but it used to on version 3

**Comment by ChiefGyk** [comment]
[1]+  Exit 1                  sudo /opt/vc/bin/vcgencmd measure_temp
sudo: /opt/vc/bin/vcgencmd: command not found

**Comment by ChiefGyk** [comment]
This is incompatible with Armbian, we should consider pulling from a hardware agnostic place. 
`cat /sys/devices/virtual/thermal/thermal_zone0/temp`
 should work fine, if we can divide that number 1000 that's the celsius number. Also worth considering an HDD temp sensor for the Odroid HC2 crowd.

**Comment by shermand100** [comment]
There are so many files in that merge request so I've used your suggestion and added it directly
