### ISSUE TITLE
Enable blocking of malicious nodes by default

### ISSUE THREAD

**Issue by viperperidot** [monero-ecosystem/PiNode-XMR#29]
As seen in this recent Reddit post and discussions on IRC there has been known malicious nodes on the Monero network (https://old.reddit.com/r/Monero/comments/jrh7mv/psa_informational_thread_on_the_recently_observed/).

The dev team has come out with a --ban-list flag to start monerod and block the IPs of all the known bad actors. More details on what these bad actors can do can be found in the Reddit post.

I think this should be a high priority to have this flag added to all startup scripts of monerod on PiNodeXMR. I know several users have reported having sync freezing issues which seems to be one of the things these bad nodes can accomplish if you happen to connect to one.

Lets get these bad nodes off our network!!

**Comment by shermand100** [comment]
As this is an ongoing issue yet to be solved purely by Monerod commits I agree that temporary measures such as this can be taken to improve user experience.

--ban-list has been added to all startup scripts with reference to Selsta's block.txt

Raspbian --ban-list commit https://github.com/monero-ecosystem/PiNode-XMR/commit/3b8b3d06791c5e429b0a3294fa81b896f1dc9aa5

Armbian --ban-list commit https://github.com/monero-ecosystem/PiNode-XMR/commit/af038b6c2808223d7d460e0417bf8f1ce1396aac

In addition to this an extra crontab entry has been added for daily auto updates (at 00:00) to the file block.txt ensuring any new malicious nodes are excluded from our network.

Raspbian crontab new entry https://github.com/monero-ecosystem/PiNode-XMR/commit/5b854582338264e9a1e49e0ced27200e8ebfedbb

Armbian crontab new entry https://github.com/monero-ecosystem/PiNode-XMR/commit/a6551f8b25854bf400205cc501a90f44b47cbe67
