### ISSUE TITLE
Pruning doesn't work for public free node type

### ISSUE THREAD

**Issue by PidgeyBE** [monero-ecosystem/PiNode-XMR#33]
I've activated pruning, but the ` --prune-blockchain` argument didn't appear in `htop` or in `monerod-start-public-free.sh`. It did appear in the other `monerod-start*.sh` files...
I have a Raspberry Pi4.

Everything else seems to work! Thanks a lot, Pidgey

**Comment by shermand100** [comment]
Hi thanks for that. I've corrected it for public free and also i2p https://github.com/monero-ecosystem/PiNode-XMR/commit/a87eb8567163797f0ddc389340126841572aa3b8
