### ISSUE TITLE
Connection Error 200

### ISSUE THREAD

**Issue by wsking0110** [monero-ecosystem/PiNode-XMR#35]
I am trying to connect to my local node. I am able to successfully test it, showing that the node is active and login/password works. (When I change the login info it gives a connection error) However, it gives a connection error 200 after I add the node when trying to connect. All devices on the same network. I also notice the height is 0 (v0) where other good nodes show a number. Reformat SD/Reinstall does not help. I have tried running private, with and without tor - on monerujo and the official monero-gui both windows and tails. In no scenario can I get a wallet to connect to my node.

**Comment by shermand100** [comment]
Ok so there's a lot going on in that question. What mode of Monero node do you want to run from the start button? (ideally)

When you're connecting a wallet has the node finished syncing?

**Comment by wsking0110** [comment]
Initially I am just trying to get private node rpc login to work. My real goal is to use tor private node mode to run the mobile wallet through orbot android, and have the node post the transaction via tor. Once I accomplish that I want to run it in free public mode when its not being used for something else.

The wallet has finished syncing, yes

Upon further testing, it seems the issue is with the monerujo wallet moreso than the pinodexmr. I am able to get mobile cake wallet to connect to pinodexmr. I can also get the monero gui that I added to tails to connect to the node using the same address/login info as used on the cake wallet. Its just monerujo that gives the connection 200 error, after the test node function is successful (pings <20ms but with 0 (v0) height)

For now, im just going to use cake wallet and monero gui.

Thanks for the reply.

**Comment by shermand100** [comment]
@wsking0110 
How are you getting on?
Do you need any further help with the PiNodeXMR side of this, or was this a Monerujo issue?

**Comment by wsking0110** [comment]
I stopped using monerujo in favor of the desktop monero GUI. I am still waiting g for my daemon to sync for the first time. It has been almost a week so far. I'm hoping once that completes it will be smooth sailing from there.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by shermand100** [comment]
Hi @wsking0110 , just doing a trawl of these issues. How are you getting on? Do you need further help or can this be closed?

**Comment by wsking0110** [comment]
Close it. I'm about to retry all this with the rock pro 64

Sent from ProtonMail mobile

-------- Original Message --------
