### ISSUE TITLE
Swap setting persistence

### ISSUE THREAD

**Issue by philkode** [monero-ecosystem/PiNode-XMR#38]
Hey. Been using PiNode for a while now and really loving how easy it makes it to run a node. Just a small issue/request. I notice that the swap setting doesn't seem to persist on a reboot (i.e. I turn it off, then if the Pi is restarted the swap comes back).

Would be good if this setting was persistent and remembered between reboots.

All the best!

**Comment by shermand100** [comment]
Hi there, thanks for the feedback. And yes that's an obvious inconvenience but a simple one to fix. I've committed the changes needed:

Raspbian branch https://github.com/monero-ecosystem/PiNode-XMR/commit/c312b2a98b6b86936f7b756e4da30bc3d4330331
Armbian branch https://github.com/monero-ecosystem/PiNode-XMR/commit/cc2928a90ec47ff7f3152815f5b2988b5ce3dfe0

All feedback to make this project better is appreciated.

**Comment by ChiefGyk** [comment]
I had to do it through Systemd when I have time I'll try and find the documentation for what I had to do a couple days ago myself

**Comment by shermand100** [comment]
The commits in the comment above should have resolved this. They did on my Raspberry Pi OS build, simple my using systemd enable/disable to launch the appropriate condition on boot.
This can be closed on confirming it works for someone else too.
@ChiefGyk If your build was downloaded recently (less than 10 days ago) you'll have this update and should have persistence of the setting you choose.

**Comment by shermand100** [comment]
As mentioned in the second comment this issue should have been solved by commits.
No feedback heard, assume all good. Will re-open if this persists for some reason. Closing.
