### ISSUE TITLE
Hash info on pre-installed disk image (PiNode-XMR_v3.20.04.img) does not match

### ISSUE THREAD

**Issue by GitHub-Vadrigar** [monero-ecosystem/PiNode-XMR#4]
Hi!

It seems like the provided hash info does not match the recently updated disk image provided by the link below:
https://github.com/monero-ecosystem/PiNode-XMR#pinode-xmr-v32004

The generated SHA256 of PiNodeXMR_v3.20.04.img should be 77a38c7dc1cbd5e41c6f7ad33a0b41b3f9ee71a91911597196ce74be92114592

Please confirm the correct hash

With kind regards,
Vadrigar

**Comment by shermand100** [comment]
Thanks for noticing that. 
I've checked the source on google drive hasn't changed and double checked the hashes.

I've updated to show the correct hash. Yours is correct.

Thanks
