### ISSUE TITLE
Block explorer seems to be broken

### ISSUE THREAD

**Issue by dalecooper** [monero-ecosystem/PiNode-XMR#5]
Whenever I try to see the details of a block, the process stops. I can see it disappear with
`watch "ps aux | grep xmrblocks"`

A few seconds later it starts again, until I try to watch a block.
The home page works well though.
Also, not sure if this is related or not, but one of the arguments seems incorrect to me :

--**deamon**-url=HTTP://192.168.0.179:18081

Edit : should have checked before, but transactions are OK

**Comment by shermand100** [comment]
Thanks for letting me know. I'll look into it.
Systemd will restart the xmrblocks process if it fails, but if it's fundamentally not working then that's no use to anyone.

**Comment by shermand100** [comment]
@dalecooper 
I've investigated all I can and think it's a bug limited to every block above 1978432 (post randomx upgrade).

I've raised the issue with the block explorer creator at his github project as there are no open/closed issues related. So unless it's our user error the fix should come from there.

https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/211

**Comment by dalecooper** [comment]
Thank you, can confirm that it works well with blocks up to 1978432 indeed

**Comment by shermand100** [comment]
Still working on this. Not forgotten.
Block explorer works correctly at all heights on 64 bit system (Odroid XU4).
Error persists at block 1978433 (post randomx upgrade) and up for 32-bit systems (Raspberry Pi3/4) or limited to Raspberry Pi OS

**Comment by shermand100** [comment]
Ok, this can finally be closed.
Between PiNodeXMR using Ubuntu 22.04LTS Server OS as it's base and Monero upgrading to v0.18.0.0 this issue no longer persists.
Explorer works fine on RPi3 with 32bit OS and all 64 bit devices and images.

Finally this period of stability can be enjoyed.
