### ISSUE TITLE
Updating Onion Block Explorer to latest version fails, error is ignored

### ISSUE THREAD

**Issue by nkinnan** [monero-ecosystem/PiNode-XMR#52]
The error is not caught, pinodexmr thinks the update was successful.  Additionally I'm not sure how to correct this, or if it's a setup issue in pinodexmr or if it's an issue with the block explorer.  

Console output:
[onionerr.txt](https://github.com/monero-ecosystem/PiNode-XMR/files/7923987/onionerr.txt)

If there are additional logs or anything I can grab, please let me know.

**Comment by nkinnan** [comment]
I think this is a duplicate of #46?

**Comment by nkinnan** [comment]
Is there a solution to get the block explorer running?  Downgrading to a previous version or something?  I didn't test if it worked before I tried upgrading, so I'm not even sure if a reflash would help or not.

**Comment by shermand100** [comment]
This is known and temporary whilst we are using the Monero pre-built binaries.
The block explorer requires Monero to be built from source (hence all the NOT FOUND in your log), currently building Monero from source on Debian Bullseye crashes Monero.

The block explorer function will return, but cannot currently be installed, updated or used. Sorry.
I'll leave this open for visibility

**Comment by shermand100** [comment]
Note to users that come across this. Block explorer fails on RPi due to core CPU issues in handling 64bit crypto.
A Pi, Ubuntu 32bit 22.04 LTS OS as the base to build PiNodeXMR upon successfully compiles and runs the Block Explorer.

**Comment by satrinity402** [comment]
@shermand100 I just opened an issue with the block explorer. I'm running a Rpi4 and Ubuntu server 64 bit LTS OS. Will there ever be a fix for the 64 bit OS?

**Comment by shermand100** [comment]
The initial error here should not exist anymore and furthermore, full testing has been carried out on the Onion-blockexplorer master branch with Monero release-v0.18 on:
R Pi3b+ with Ubuntu 22.04 LTS 32-bit
R Pi4 with Ubuntu 22.04 LTS 64-bit
Odroid XU4 with Ubuntu 22.04 LTS 32-bit
RockPro64 with Ubuntu 22.04 LTS 64-bit
Rock64 with Ubuntu 22.04 LTS 64-bit

An update of PiNodeXMR v5, then update of Block Explorer should solve all problems
