### ISSUE TITLE
Magnet Link Not Working

### ISSUE THREAD

**Issue by velamvela** [monero-ecosystem/PiNode-XMR#53]
The magnet link is not working for me, can someone confirm if it is valid?

https://github.com/monero-ecosystem/PiNode-XMR/wiki/Manual#downloads

[magnet:?xt=urn:btih:494ca720db6053f892393aebc9c9129a1323def4&dn=PiNodeXMR-v4.21.01-prunedToBlock2278908.zip&tr=udp%3a%2f%2f9.rarbg.to%3a2710%2fannounce&tr=udp%3a%2f%2f9.rarbg.me%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.internetwarriors.net%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.cyberia.is%3a6969%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce&tr=udp%3a%2f%2f3rt.tace.ru%3a60889%2fannounce&tr=http%3a%2f%2f5rt.tace.ru%3a60889%2fannounce&tr=udp%3a%2f%2fexplodie.org%3a6969%2fannounce&tr=udp%3a%2f%2fp4p.arenabg.ch%3a1337%2fannounce&tr=http%3a%2f%2fp4p.arenabg.com%3a1337%2fannounce&tr=udp%3a%2f%2ftracker2.itzmx.com%3a6961%2fannounce&tr=udp%3a%2f%2f47.ip-51-68-199.eu%3a6969%2fannounce&tr=http%3a%2f%2fopen.acgnxtracker.com%3a80%2fannounce&tr=udp%3a%2f%2fwww.torrent.eu.org%3a451%2fannounce&tr=udp%3a%2f%2ftracker.torrent.eu.org%3a451%2fannounce&tr=udp%3a%2f%2ftracker.tiny-vps.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.ds.is%3a6969%2fannounce&tr=udp%3a%2f%2fopen.stealth.si%3a80%2fannounce&tr=http%3a%2f%2fopentracker.i2p.rocks]

**Comment by shermand100** [comment]
Hi there, sorry for the delay. That link was supported by another community member and I'm not sure how popular the methods was. It may be a bit hit and miss.

When it was set up I personally checked the generated hashes to confirm it is the same image as the one available on the direct download link. It's hosted by google so hope the speed is ok.

Those images though a little outdated by now and I really should produce a new one. I'd recommend flashing the most up-to-date OS and installing from the command line command.

**Comment by shermand100** [comment]
PiNode.co.uk website re-designed and this github repo now has images as direct downloads.
The torrent option was trailed but very few seeders and became unreliable.
Still need to find suitable hosting solution.
