### ISSUE TITLE
Monerod not found after upgrade

### ISSUE THREAD

**Issue by ChiefGyk3D** [monero-ecosystem/PiNode-XMR#64]
After upgrading Monero via the built in upgraded I keep getting
./monerod-start-tor.sh: line 33: ./monero/build/release/bin/monerod: No such file or directory

With an ls revealing for some reason all the files were deleted

**Comment by shermand100** [comment]
Ok, thanks for the issue.
I can take proper look this afternoon.
The updater, if a user requests it or the current monero version on the PiNodeXMR is lower than current latest does these things:

* Stop currently running node
* Deletes contents of /monero dir
* Either builds Monero from source or downloads the pre-compiled monero. 

It sounds likely the third step there isn't happening. In the updater menu are you asking to "Force Update" or did it just start updating as it found a new version? That would help me with which part of the script I need to target (but it looks like it all cold do with reviewing).

Thanks.

**Comment by shermand100** [comment]
Culprit seems to have been found.

`mv: cannot stat '/home/pinodexmr/temp/monero-aarch64-linux-gnu-v0.17.3.0/monero*': No such file or directory`

PiNodeXMR extracts the `linuxarm7 `or `linuxarm8 ` to a dir called "temp"

Monero version and extracted folder format is now "monero-aarch64-linux-gnu-v0.17.3.**2**/"

Fix Armbian: https://github.com/monero-ecosystem/PiNode-XMR/commit/ebaf70f3da950e5abe96ef274630cc837fc1bf2b
Fix Raspbian: https://github.com/monero-ecosystem/PiNode-XMR/commit/3c606ad76e85737de975fceab53bc6ee34cd7bd3

Pre-emptively Fixed Ubuntu branch (committed but not yet pushed) along with first installer scripts.

Just testing now but I don't expect further issues.

**Comment by ChiefGyk3D** [comment]
Just saw this, going to try and update it again as I am prepping my staging node for Monero upgrades and the upcoming hard fork

**Comment by shermand100** [comment]
As far as I'm aware this no longer occurs as the path was fixed.
Making a note to myself to ensure as new tagged releases are available to update the path of unpacking the Monero directory
