### ISSUE TITLE
Add basic authentication to the web console

### ISSUE THREAD

**Issue by devinpearson** [monero-ecosystem/PiNode-XMR#68]
Add optional user authentication to the web console.

Suppose one uses the node on a publicly accessible network or in a shared environment. In that case, they should be able to enable basic authentication to prevent their node from being controlled.

**Comment by shermand100** [comment]
I'd been playing with options and think I've covered user interactions I can think of:

- User can set password
- User can change password
- User can Enable/Disable Password requirement
- User can run PiNodeXMR Updater script and password requirement state is maintained

The method used here is clunky but functional in overwriting 000-default.conf with a file version with the required block (simply commented in/out):

>     <Directory "/var/www/html">
>         AuthType Basic
>         AuthName "Restricted Content"
>         AuthUserFile /etc/apache2/.htpasswd
>         Require valid-user
>     </Directory>

I tried messing around with removing the comment `#` tag from the desired lines with 'sed' string searches but actually got messier than just overwriting the file. As in this PR:

https://github.com/monero-ecosystem/PiNode-XMR/pull/75

Is there a better way. If it'll do the job then I'll merge it in.

**Comment by shermand100** [comment]
Reviewing this feature request.
Did some more basic testing:

From the terminal Settings Menu -> Extra network tools.

- User can Create/Update a password for HTML Auth (Username is always 'pinodexmr')
- User can enable the password requirement
- User can disable the password requirement


As always we can re-open this should further development be needed.
