### ISSUE TITLE
updating Monero not properly reported

### ISSUE THREAD

**Issue by roudaille79** [monero-ecosystem/PiNode-XMR#7]
Hi, after last Monero update, web interface shows wrong release
![2020-10-20_16h28_28](https://user-images.githubusercontent.com/57755767/96601046-e696e880-12f1-11eb-9960-69b5e04b1b98.png)

**Comment by shermand100** [comment]
Hi there. I have very returned from working abroad and am now 100% working on improving PiNodeXMR.

The Monero version status you show there is a command run every 4 hours. It is not run too often to save on device resources as the output unless Monero is updated doesn't change often. You may find that this catches up soon.
Alternatively web browsers cache this sort of text info so you can right-click on that staus and then "reload frame" get get the new status.

However I am aware that updating to v0.17 has caused some stability issues and I am currently debugging this. If this is the case that the Monero v0.17.x.x has crashed and so the old version is still displayed I hope to have a fix for this soon.

PiNodeXMR uses only the current official Monero-cli, I never alter/edit it, so I hope to get this fixed soon.

**Comment by roudaille79** [comment]
thank you for your feedback. The fact is that it happened before when upgraded to 0.16.x. So this release version is printed since months

**Comment by shermand100** [comment]
This shouldn't happen again:

When updating from now on the current version variable is updated on the installing branch so new users get the correct version, and the new version is updated to prompt existing users.

The main Monero release is tagged on our master branch so source builds are correct and the tar package version is updated in the updater script and installer scripts. I have a fairly robust system for this and don't see this happening again.
