### ISSUE TITLE
Updating Monero on node results in small syntax error at start 

### ISSUE THREAD

**Issue by ChiefGyk3D** [monero-ecosystem/PiNode-XMR#71]
```
2022-06-10 14:34:25 (1.48 MB/s) - ‘/home/pinodexmr/new-ver-pi.sh’ saved [33/33]

Update system version number
Success
Cleanup leftover directories
Success
bash: line 279: syntax error near unexpected token `else'
bash: line 279: `	else'
rm: cannot remove '/home/pinodexmr/new-ver-pi.sh': No such file or directory
```

I replicated this on both of my nodes doing the monero update via setup when updating to .17.3.2 to prepare for .18 coming out soon for testing

**Comment by shermand100** [comment]
Thanks for that good spot.

Closing 'fi' for 'if statement' missing from line 259 was culprit.

Other minor formatting changes in same commit.

I can re-open if you still encounter this error
