### ISSUE TITLE
[Feature Request] New screen that gives you the ability to run monero daemon commands

### ISSUE THREAD

**Issue by satrinity402** [monero-ecosystem/PiNode-XMR#72]
Example: If I want to run the print_coinbase_tx_sum daemon command, there is no way to do so unless I perform the following steps:

1. Stop my node
2. Manually connect via SSH
3. run ./monerod manually
4. execute daemon commands once synced

Would be awesome if we could run commands directly from a command line of sorts, right from the UI, without needing to stop/manually start monerod.

**Comment by shermand100** [comment]
You should be able to leave your node running.
The web terminal included with the Web-UI should also simplify ssh-ing to pass your command:

 The following format can be used....

(It all depends on what mode you're running in, but for "public  free mode" for example and output:

```
pinodexmr@PiNodeXMR:~$ ./monero/build/release/bin/monerod --rpc-bind-ip=192.168.1.104 --rpc-bind-port=18089 --rpc-ssl disabled print_coinbase_tx_sum 0 100
2022-06-16 22:38:25.837 I Monero 'Oxygen Orion' (v0.17.3.2-release)
Sum of coinbase transactions between block heights [0, 100) is 1759.135559809471 consisting of 1759.135559809471 in emissions, and 0.000000000000 in fees
pinodexmr@PiNodeXMR:~$
```

Where the port 18089 is the **unrestriced** port number, local IP is the the PiNodeXMR device.

All commands listed here...
https://monerodocs.org/interacting/monerod-reference/
Should be available in this way.

```
pinodexmr@PiNodeXMR:~$ ./monero/build/release/bin/monerod --rpc-bind-ip=192.168.1.104 --rpc-bind-port=18089 --rpc-ssl disabled hard_fork_info
2022-06-16 22:47:46.763 I Monero 'Oxygen Orion' (v0.17.3.2-release)
version 14 enabled, 10080/10080 votes, threshold 0
current version 14, voting for version 14
pinodexmr@PiNodeXMR:~$
```

Does that answer your question? The format isn't that clean but follows a simple and necessary pattern.

**Comment by satrinity402** [comment]
I think that makes sense, cheers @shermand100
