### ISSUE TITLE
usb not mounting

### ISSUE THREAD

**Issue by dawiepoolman** [monero-ecosystem/PiNode-XMR#78]
hi @shermand100
when mounting the usb (i.e. an SSD) to my RPi3B I saw the script leaves successfully but I spotted an error in the console:

Labeling drive 'XMRBLOCKCHAIN'...
Mounting Device...Please Wait...
/home/pinodexmr/setupMenuScripts/setup-usb.sh: line 230: syntax error near unexpected token `fi'
/home/pinodexmr/setupMenuScripts/setup-usb.sh: line 230: `fi'

I then checked 
sudo nano /etc/fstab
UUID=
(i.e. the UUID was missing)

I had to find it manually using
sudo blkid

hence on reboot the mounting was missing for:
/dev/sda/sda1 /home/pinodexmr/.bitmonero

hope this helps finding the issue

**Comment by shermand100** [comment]
Hi, I've been through the file and matched up all 'if' and 'fi' and there was indeed an extra 'fi' on line 230.

Amended in commit 8afe04dc8f60b64fbbc958f4bac4105209943af4

On update this should no longer be a problem.
