### ISSUE TITLE
Cannot get Block Explorer to work

### ISSUE THREAD

**Issue by satrinity402** [monero-ecosystem/PiNode-XMR#79]
After a fresh install of PiNodeXMR, and updating the Block Explorer to the latest version via the CLI menu, I am still getting the following message on the Node Status page:

**Explorer    :  activating (auto-restart) (Result: exit-code) since Sat 2022-07-02 12:56:30 MST; 2min 31s ago**

I've tried rebooting, stopping and starting the block explorer, but am unable to get it to work.

**Comment by satrinity402** [comment]
Hardware: Raspberry Pi 4 4GB, 1 TB SSD w/ power supply, 32GB SD Card
OS: Ubuntu server 22.04 LTS 64 bit

**Comment by satrinity402** [comment]
Some errors (also added in TG channel): 

terminate called after throwing an instance of 'boost::wrapexcept<boost::program_options::unknown_option>'
  what():  unrecognised option '--deamon-url=HTTP://XXX.XXX.XX.XX:18081'
blockExplorer.sh: line 31: 138481 Aborted                 (core dumped) ./xmrblocks --port 8081 --enable-pusher --enable-emission-monitor --deamon-url=HTTP://${DEVICE_IP// }:$MONERO_PORT --daemon-login $RPCu:$RPCp --mempool-info-timeout 60000 --mempool-refresh-time 30 --concurrency 1

**Comment by shermand100** [comment]
If this is indeed due to the Daemon/deamon typo this should already be fixed as of:

https://github.com/monero-ecosystem/PiNode-XMR/pull/77/commits/5228b6f62050ed471667c370cc27b86126b34145

And you were unfortunate enough to have the code pre-commit of this fix.

**Comment by satrinity402** [comment]
Thank you! 

Updated the 'home/pinodexmr/execScripts/blockExplorer.sh' script and fixed the typo. Working great now!
