### ISSUE TITLE
**Bug** Sync status update issue

### ISSUE THREAD

**Issue by ghost** [monero-ecosystem/PiNode-XMR#83]
After a fresh install, and after starting Monerod, the sync status tab of the dashboard does not auto update within the mentioned 5 minutes. A browser cache reset has to be performed before the dashboard will show status.

**Comment by shermand100** [comment]
The browser doesn't auto update at all. Manual update is required.

The purpose of the:

https://github.com/monero-ecosystem/PiNode-XMR/blob/ubuntuServer-20.04/HTML/.htaccess

file is to prevent browser caching so removing the need to clear the cache manually. I find this works quite reliably in chrome.

What browser do you use? It may require further tweaking.
